  spring:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ies
      username: root
      password: Twister@123

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true  